// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osuyeptufjtmqsydulmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zdXllcHR1Zmp0bXFzeWR1bG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MjI2ODUsImV4cCI6MjA2Njk5ODY4NX0.oN4Kh-u4pQ_CGqv7anpEVcYatzZpaWeZrxrQMPRWu7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Function to set custom JWT from Clerk
export const setSupabaseAuth = async (token: string | null) => {
  if (token) {
    // Set custom auth token for Supabase
    await supabase.auth.setSession({
      access_token: token,
      refresh_token: token, // For custom JWT, we use the same token
    });
  } else {
    // Clear auth
    await supabase.auth.signOut();
  }
};